# Generated by Django 5.2.17 on 2026-09-12 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attempt',
            name='review_positions',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='profile',
            name='language',
            field=models.CharField(choices=[('uz', 'O‘zbekcha'), ('en', 'English'), ('ru', 'Русский')], default='uz', max_length=2),
        ),
        migrations.AddField(
            model_name='profile',
            name='target_band',
            field=models.DecimalField(decimal_places=1, default=7, max_digits=2),
        ),
        migrations.AlterField(
            model_name='question',
            name='accepted_answers',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
