# Generated by Django 5.2.17 on 2026-09-12 10:39

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0002_attempt_review_positions_profile_language_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssessmentJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(default='pending', max_length=16)),
                ('tries', models.PositiveIntegerField(default=0)),
                ('available_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('lease', models.UUIDField(blank=True, null=True)),
                ('error_code', models.CharField(blank=True, max_length=64)),
                ('attempt', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='assessment_job', to='exams.attempt')),
            ],
        ),
    ]
