# Generated by Django 5.2.17 on 2026-09-14 04:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0004_profile_avatar_profile_city_profile_institution_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpeakingRecording',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('segments', models.JSONField(default=list)),
                ('attempt', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='speaking_recording', to='exams.attempt')),
            ],
        ),
    ]
