# Generated by Django 5.2.17 on 2026-09-28 11:38

import django.core.validators
import exams.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0007_normalize_demo_audio_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='audio_file',
            field=models.FileField(blank=True, upload_to='exam_audio/', validators=[django.core.validators.FileExtensionValidator(['mp3', 'wav', 'ogg', 'm4a', 'webm']), exams.validators.validate_audio_upload]),
        ),
    ]
