# Generated by Django 5.2.17 on 2026-09-30 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0008_alter_exam_audio_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='listening_transcript',
            field=models.TextField(blank=True),
        ),
    ]
