# Generated by Django 5.2.17 on 2026-09-30 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0009_exam_listening_transcript'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpeakingSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=180)),
                ('version', models.PositiveIntegerField(default=1)),
                ('published', models.BooleanField(default=False)),
                ('part1_questions', models.JSONField(default=list)),
                ('cue_title', models.CharField(max_length=500)),
                ('cue_points', models.JSONField(default=list)),
                ('part3_questions', models.JSONField(default=list)),
            ],
            options={
                'verbose_name': 'Speaking savol to‘plami',
                'verbose_name_plural': 'Speaking savol to‘plamlari',
            },
        ),
    ]
