'use client';
import {useEffect,useState} from 'react';
import {ArrowRight,TrendingUp} from 'lucide-react';
import {api,type Language} from './api';
import LoadingSkeleton from './loading-skeleton';
type Point={id:string;date:string;value:number;title:string};
type Series={id:string;metric:'raw'|'ai_band';maximum:number;title?:string;version?:number;scope?:string;model?:string;rubric?:string;points:Point[]};
type Module={section:string;series:Series[]};
const labels={
 uz:{title:'Rivojlanish tahlili',note:'Oxirgi 100 ta baholangan urinish. Turli testlar va AI baholash usullari alohida ko‘rsatiladi.',loading:'Analitika yuklanmoqda…',retry:'Qayta urinish',empty:'Bu bo‘limda baholangan natija yo‘q.',series:'Taqqoslash guruhi',raw:'To‘g‘ri javoblar',ai:'AI band taxmini',change:'Birinchi urinishga nisbatan',single:'O‘zgarishni ko‘rish uchun shu guruhda yana bir natija kerak.',date:'Sana',result:'Natija',open:'Tahlilni ochish',table:'Barcha nuqtalarni jadvalda ko‘rish',section:'To‘liq bo‘lim',tasks:'Alohida topshiriqlar',unknown:'Alohida baholash',disclaimer:'Bir xil testni qayta ishlash natijaga ta’sir qilishi mumkin. Bu grafik rasmiy IELTS darajasini tasdiqlamaydi.'},
 en:{title:'Progress analytics',note:'Latest 100 graded attempts. Different tests and AI assessment methods are shown separately.',loading:'Loading analytics…',retry:'Try again',empty:'No graded results for this section.',series:'Comparison group',raw:'Correct answers',ai:'Estimated AI band',change:'Change from first attempt',single:'One more result in this group is needed to show change.',date:'Date',result:'Result',open:'Open analysis',table:'View every point in a table',section:'Full section',tasks:'Individual tasks',unknown:'Separate assessment',disclaimer:'Repeating the same test can affect the result. This chart does not establish an official IELTS level.'},
 ru:{title:'Аналитика прогресса',note:'Последние 100 проверенных попыток. Разные тесты и методы оценки ИИ показаны отдельно.',loading:'Загрузка аналитики…',retry:'Повторить',empty:'В этом разделе нет проверенных результатов.',series:'Группа сравнения',raw:'Правильные ответы',ai:'Оценка band от ИИ',change:'Изменение с первой попытки',single:'Для сравнения нужен ещё один результат в этой группе.',date:'Дата',result:'Результат',open:'Открыть анализ',table:'Посмотреть все точки в таблице',section:'Полный раздел',tasks:'Отдельные задания',unknown:'Отдельная оценка',disclaimer:'Повторение одного теста может повлиять на результат. График не подтверждает официальный уровень IELTS.'}
};
export default function AnalyticsDashboard({language,onOpen,busy}:{language:Language;onOpen:(id:string)=>void;busy:boolean}){
 const [modules,setModules]=useState<Module[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState(''),[retry,setRetry]=useState(0);
 const t=labels[language];
 useEffect(()=>{let alive=true;setLoading(true);setError('');api<{modules:Module[]}>('analytics/').then(data=>{if(alive)setModules(data.modules)}).catch(e=>{if(alive)setError(e.message)}).finally(()=>{if(alive)setLoading(false)});return()=>{alive=false}},[retry]);
 if(loading)return <LoadingSkeleton label={t.loading}/>;
 return <><div className="page-heading"><div><h1>{t.title}</h1><p>{t.note}</p></div><TrendingUp size={28}/></div>{error?<div className="product-alert" role="alert">{error}<button className="secondary" onClick={()=>setRetry(n=>n+1)}>{t.retry}</button></div>:<div className="analytics-grid">{modules.map(module=><ModuleChart key={module.section} module={module} language={language} onOpen={onOpen} busy={busy}/>)}</div>}<p className="product-muted">{t.disclaimer}</p></>;
}
function ModuleChart({module,language,onOpen,busy}:{module:Module;language:Language;onOpen:(id:string)=>void;busy:boolean}){
 const [selected,setSelected]=useState('');const t=labels[language];
 const series=module.series.find(s=>s.id===selected)||module.series[module.series.length-1];
 if(!series)return <section className="panel analytics-empty"><h2>{module.section}</h2><p>{t.empty}</p></section>;
 const points=series.points,first=points[0],last=points[points.length-1],delta=last.value-first.value;
 const unit=series.metric==='raw'?t.raw:t.ai;
 const coordinates=points.map((p,i)=>({x:points.length===1?220:40+i*360/(points.length-1),y:160-p.value/series.maximum*136}));
 const seriesLabel=(s:Series)=>s.metric==='raw'?`${s.title} · v${s.version}`:`${s.scope==='writing_section'?t.section:s.scope==='submitted_tasks_only'?t.tasks:t.unknown} · ${s.model} · ${s.rubric}`;
 return <section className="panel analytics-module"><div className="section-title"><h2>{module.section}</h2><span className="badge">{unit}</span></div><label className="analytics-select">{t.series}<select value={series.id} onChange={e=>setSelected(e.target.value)}>{module.series.map(s=><option value={s.id} key={s.id}>{seriesLabel(s)}</option>)}</select></label><div className="analytics-value"><strong>{last.value}{series.metric==='raw'&&<small> / {series.maximum}</small>}</strong><p>{points.length>1?`${delta>0?'+':''}${Number(delta.toFixed(2))} · ${t.change}`:t.single}</p></div><svg className="analytics-chart" viewBox="0 0 440 200" role="img" aria-label={`${module.section}: ${first.value} → ${last.value}. ${unit}`}><title>{module.section} · {unit}</title>{[0,.5,1].map(f=><g key={f}><line x1="40" y1={160-136*f} x2="400" y2={160-136*f} className="chart-gridline"/><text x="32" y={164-136*f} textAnchor="end">{series.maximum*f}</text></g>)}{points.length>1&&<polyline points={coordinates.map(p=>`${p.x},${p.y}`).join(' ')} className="chart-line"/>}{coordinates.map((c,i)=><circle key={points[i].id} cx={c.x} cy={c.y} r="4" className="chart-point"><title>{new Date(points[i].date).toLocaleDateString(language)}: {points[i].value}</title></circle>)}<text x="40" y="192">{new Date(first.date).toLocaleDateString(language)}</text>{points.length>1&&<text x="400" y="192" textAnchor="end">{new Date(last.date).toLocaleDateString(language)}</text>}</svg><details><summary>{t.table} ({points.length})</summary><div className="analytics-table-wrap"><table><caption>{module.section} · {unit}</caption><thead><tr><th>{t.date}</th><th>{t.result}</th><th>{t.open}</th></tr></thead><tbody>{points.map(p=><tr key={p.id}><td>{new Date(p.date).toLocaleString(language)}</td><td>{p.value}{series.metric==='raw'?` / ${series.maximum}`:''}</td><td><button className="text-button" disabled={busy} onClick={()=>onOpen(p.id)} aria-label={`${t.open}: ${p.title}`}><ArrowRight size={18}/></button></td></tr>)}</tbody></table></div></details></section>;
}
