'use client';
import {useCallback,useEffect,useState} from 'react';
import {ArrowRight,BookOpen,CalendarDays,Home,LogOut,MessageSquare,Plus,Settings2,Target,UserRound,BarChart3} from 'lucide-react';
import {api,type Attempt,type Exam,type Language,type User} from './api';
import {copy} from './i18n';
import ExamRunner from './exam-runner';
import ResultReport from './result-report';
type View='dashboard'|'tests'|'results'|'plan'|'profile';
export default function ProductApp(){
 const [user,setUser]=useState<User|null>(null),[language,setLanguage]=useState<Language>('uz'),[view,setView]=useState<View>('dashboard'),[ready,setReady]=useState(false),[available,setAvailable]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState(''),[register,setRegister]=useState(false),[exams,setExams]=useState<Exam[]>([]),[history,setHistory]=useState<Attempt[]>([]),[free,setFree]=useState(false),[active,setActive]=useState<Attempt|null>(null);
 const t=copy[language];
 const load=useCallback(async()=>{const [cat,list]=await Promise.all([api<{exams:Exam[];free_attempt_available:boolean}>('catalog/'),api<{attempts:Attempt[]}>('attempts/')]);setExams(cat.exams);setFree(cat.free_attempt_available);setHistory(list.attempts)},[]);
 const connect=useCallback(async()=>{setReady(false);setError('');try{const s=await api<{user:User|null}>('session/');setAvailable(true);setUser(s.user);if(s.user){setLanguage(s.user.language);await load()}}catch(e){setAvailable(false);setError((e as Error).message)}finally{setReady(true)}},[load]);
 useEffect(()=>{void connect()},[connect]);
 useEffect(()=>{document.documentElement.lang=language},[language]);
 async function run(fn:()=>Promise<void>){setBusy(true);setError('');setNotice('');try{await fn()}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 const complete=useCallback((a:Attempt)=>{setActive(a);setView('results');void load().catch(e=>setError((e as Error).message))},[load]);
 function navigate(v:View){setView(v);setActive(null);window.scrollTo(0,0)}
 async function open(a:Attempt){await run(async()=>{setActive(await api<Attempt>(`attempts/${a.id}/`))})}
 async function start(exam:Exam){const writing=exam.section==='Writing';if(writing&&!window.confirm(t.writingNotice))return;await run(async()=>{setActive(await api<Attempt>('attempts/','POST',{exam_id:exam.id,accept_pending_assessment:writing}));await load()})}
 const graded=history.filter(a=>a.state==='graded'&&a.result),latest=graded[0],inExam=active?.state==='in_progress';
 const status=(a:Attempt)=>a.state==='graded'?t.graded:a.state==='in_progress'?t.progress:t.pending;
 const nav=[['dashboard',t.dashboard,Home],['tests',t.tests,BookOpen],['results',t.results,BarChart3],['plan',t.plan,CalendarDays],['profile',t.profile,UserRound]] as const;
 const languages=<select aria-label={t.language} value={language} onChange={e=>setLanguage(e.target.value as Language)}><option value="uz">UZ</option><option value="en">EN</option><option value="ru">RU</option></select>;
 if(!ready)return <main className="product-loading"><MessageSquare size={32}/><p role="status">{t.loading}</p></main>;
 if(!available)return <main className="product-login"><section className="panel"><h1>IELTSQA</h1><h2>{t.unavailable}</h2><p>{t.unavailableNote}</p><p role="alert">{error}</p><button className="primary" onClick={()=>void connect()}>{t.retry}</button></section></main>;
 if(!user)return <main className="product-login"><div className="login-brand"><span className="product-logo"><MessageSquare/>IELTS<span>QA</span></span>{languages}<h1>{t.subtitle}</h1><p>{t.brand}</p><p className="login-skills">Listening · Reading · Writing · Speaking</p></div><form className="panel product-auth" onSubmit={e=>{e.preventDefault();const data=Object.fromEntries(new FormData(e.currentTarget));void run(async()=>{const s=await api<{user:User}>(register?'register/':'login/','POST',data);setUser(s.user);const p=await api<{user:User}>('profile/','PATCH',{language});setUser(p.user);await load()})}}><h2>{register?t.register:t.login}</h2>{error&&<p className="product-alert" role="alert">{error}</p>}{register&&<label>{t.name}<input name="name" required maxLength={80} autoComplete="name"/></label>}<label>{t.email}<input type="email" name="email" required maxLength={150} autoComplete="email"/></label><label>{t.password}<input type="password" name="password" required minLength={register?10:1} autoComplete={register?'new-password':'current-password'}/></label><button className="primary" disabled={busy}>{busy?t.working:register?t.register:t.login}<ArrowRight size={18}/></button><button className="text-button" type="button" onClick={()=>{setRegister(!register);setError('')}}>{register?t.haveAccount:t.newAccount}</button></form></main>;
 return <div className={'product-shell '+(inExam?'is-exam':'')}>
 {!inExam&&<aside className="product-sidebar no-print"><button className="product-logo" onClick={()=>navigate('dashboard')}><MessageSquare/>IELTS<span>QA</span></button><p className="sidebar-subtitle">{t.brand}</p><nav>{nav.map(([id,label,Icon])=><button key={id} aria-current={view===id?'page':undefined} onClick={()=>navigate(id)}><Icon size={20}/><span>{label}</span></button>)}</nav><div className="product-target"><Target size={23}/><span>{t.target}</span><strong>{user.target_band.toFixed(1)}</strong><button onClick={()=>navigate('profile')}>{t.profile} →</button></div>{user.is_staff&&<a className="admin-link" href="/admin/" target="_blank" rel="noreferrer"><Settings2 size={18}/>{t.admin}</a>}<div className="sidebar-person"><span className="avatar">{user.name.slice(0,1).toUpperCase()}</span><strong>{user.name}</strong></div></aside>}
 <main className="product-main">{!inExam&&<header className="product-topbar no-print"><span>{t[view]}</span><div>{languages}<button aria-label={t.logout} disabled={busy} onClick={()=>void run(async()=>{await api('logout/','POST');setUser(null);setHistory([]);setActive(null)})}><LogOut size={18}/></button></div></header>}<div className="product-body">{error&&<div className="product-alert no-print" role="alert">{error}</div>}{notice&&<div className="product-success" role="status">{notice}</div>}
 {active?inExam?<ExamRunner key={active.id} attempt={active} t={t} onClose={()=>{setActive(null);void load().catch(e=>setError((e as Error).message))}} onComplete={complete}/>:<><button className="text-button no-print" onClick={()=>setActive(null)}>← {t.back}</button><ResultReport key={active.id} attempt={active} t={t}/></>:<>
 {view==='dashboard'&&<><div className="page-heading"><div><span className="eyebrow">IELTS ACADEMIC</span><h1>{t.welcome}, {user.name}.</h1><p>{t.subtitle}</p></div><button className="primary" onClick={()=>navigate('tests')}><Plus size={18}/>{t.newExam}</button></div><div className="dashboard-summary"><section className="panel latest-result"><span className="eyebrow">{t.latest}</span>{latest?<><strong>{latest.result!.correct}<small> / {latest.result!.total}</small></strong><p>{latest.section} · {latest.title}</p><button className="text-button" disabled={busy} onClick={()=>void open(latest)}>{t.details}<ArrowRight size={16}/></button></>:<><h2>{t.noScore}</h2><p>{t.noScoreNote}</p></>}</section><section className="target-card"><Target size={23}/><span>{t.target}</span><strong>{user.target_band.toFixed(1)}</strong><button className="text-button" onClick={()=>navigate('profile')}>{t.profile}</button></section><section className="panel"><span className="eyebrow">{t.attempts}</span><strong className="attempt-count">{history.length}</strong><p>{free?t.free:t.used}</p></section></div><div className="product-skill-grid">{['Listening','Reading','Writing','Speaking'].map(name=>{const a=graded.find(a=>a.section===name);return <section className="panel" key={name}><h3>{name}</h3><strong>{a?`${a.result!.correct} / ${a.result!.total}`:'—'}</strong><p>{a?t.correct:t.noScore}</p></section>})}</div><section className="panel dashboard-next"><div><span className="eyebrow">{t.plan}</span><h2>{latest?t.planNote:t.noPlan}</h2></div><button className="secondary" onClick={()=>navigate('plan')}>{t.open}<ArrowRight size={17}/></button></section></>}
 {view==='tests'&&<><div className="page-heading"><div><h1>{t.tests}</h1><p>{free?t.free:t.used}</p></div></div><section className="full-test"><div><span className="badge">IELTS ACADEMIC</span><h2>{t.fullExam}</h2><p>{t.fullNote}</p></div><span className="badge">{t.soon}</span></section><p className="product-alert">{t.noPayments}</p><div className="product-test-grid">{exams.length?exams.map(exam=><section className="panel" key={exam.id}><span className="eyebrow">{exam.section} · v{exam.version}</span><h2>{exam.title}</h2><p>{exam.question_count} {t.questions} · {Math.round(exam.duration_seconds/60)} {t.minutes}</p>{exam.section==='Writing'&&<p className="product-muted">{t.pendingNote}</p>}<button className="primary" disabled={busy||exam.section==='Speaking'} onClick={()=>void start(exam)}>{exam.section==='Speaking'?t.speakingOff:t.start}<ArrowRight size={16}/></button></section>):<p className="panel">{t.emptyTests}</p>}</div></>}
 {view==='results'&&<><div className="page-heading"><div><h1>{t.results}</h1><p>{t.historyNote}</p></div></div><section className="panel history-panel">{history.length?<div className="history-table"><div className="history-table-head"><span>{t.tests}</span><span>{t.date}</span><span>{t.score}</span><span>{t.status}</span><span/></div>{history.map(a=><div className="history-table-row" key={a.id}><div><strong>{a.title}</strong><small>{a.section}</small></div><span>{new Date(a.started_at).toLocaleDateString(language)}</span><strong>{a.result?`${a.result.correct} / ${a.result.total}`:'—'}</strong><span>{status(a)}</span><button className="text-button" disabled={busy} onClick={()=>void open(a)}>{a.state==='in_progress'?t.resume:t.open}<ArrowRight size={15}/></button></div>)}</div>:<p>{t.emptyHistory}</p>}</section></>}
 {view==='plan'&&<><div className="page-heading"><div><h1>{t.plan}</h1><p>{latest?t.planNote:t.noPlan}</p></div></div>{latest&&<><p className="badge">{latest.title}</p>{latest.result?.weekly_plan?.length?<div className="product-plan">{Array.from({length:7},(_,i)=>{const items=latest.result!.weekly_plan!;const item=items[Math.floor(i/2)%items.length];return <section className="panel plan-day" key={i}><span className="plan-number">{String(i+1).padStart(2,'0')}</span><div><span className="eyebrow">{t.day} {i+1} · 20 {t.minutes}</span><h2>{i===6?t.results:item.tag}</h2><p>{i===6?t.reflectTask:i%2?t.practiceTask:t.reviewTask}</p><p className="product-muted">{t.questions}: {item.question_positions.join(', ')} · {item.wrong} / {item.total} {t.wrong.toLowerCase()}</p><button className="text-button" disabled={busy} onClick={()=>void open(latest)}>{t.details}<ArrowRight size={16}/></button></div></section>})}</div>:<p className="panel">{t.noMistakes}</p>}</>}</>}
 {view==='profile'&&<><div className="page-heading"><div><h1>{t.profile}</h1><p>{user.email}</p></div></div><form className="panel product-auth profile-form" onSubmit={e=>{e.preventDefault();const data=Object.fromEntries(new FormData(e.currentTarget));void run(async()=>{const result=await api<{user:User}>('profile/','PATCH',data);setUser(result.user);setLanguage(result.user.language);setNotice(copy[result.user.language].profileSaved)})}}><label>{t.name}<input name="name" defaultValue={user.name} required maxLength={80}/></label><label>{t.target}<select name="target_band" defaultValue={user.target_band}>{Array.from({length:17},(_,i)=>1+i*.5).map(n=><option key={n} value={n}>{n.toFixed(1)}</option>)}</select></label><label>{t.language}<select name="language" defaultValue={language}><option value="uz">O‘zbekcha</option><option value="en">English</option><option value="ru">Русский</option></select></label><button className="primary" disabled={busy}>{busy?t.working:t.save}</button></form></>}
 </>}{!inExam&&<footer className="product-footer">IELTSQA · {t.brand}</footer>}</div></main></div>
}
